name: chuck_example
description: Demonstrates how to use the Chuck Interceptor plugin.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  connectivity_plus: ^5.0.2

dev_dependencies:
  build_runner:
  chopper_generator:
  chuck_interceptor:
    path: ../

flutter:

  uses-material-design: true
