name: alice_example
description: Demonstrates how to use the Alice plugin.
publish_to: "none"

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  chopper: ^4.0.1
  path_provider: ^2.0.6

dev_dependencies:
  build_runner:
  chopper_generator:
  chuck_interceptor:
    path: ../

flutter:

  uses-material-design: true
