name: chuck_example
description: Demonstrates how to use the Chuck Interceptor plugin.
publish_to: "none"
version: 2.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.15
  connectivity_plus: ^4.0.1

dev_dependencies:
  build_runner:
  chopper_generator:
  chuck_interceptor:
    path: ../

flutter:

  uses-material-design: true
