name: chuck_interceptor
description: Chuck is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 1.1.1
homepage: https://github.com/SunnatilloShavkatov/chuck_interceptor

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ">=0.13.5-0 <2.0.0"
  dio: ">=4.0.6-0 <6.0.0"
  flutter_local_notifications: ">=12.0.0-0 <15.0.0"
  rxdart: ^0.27.6
  path_provider: ^2.0.11
  permission_handler: ">=10.1.0-0 <14.0.0"
  package_info_plus: ">=3.0.0-0 <6.0.0"
  share_plus: ">=6.0.0-0 <10.0.0"

dev_dependencies:
  flutter_lints: ^2.0.1