name: chuck_interceptor
description: Chuck is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 1.0.2
homepage: https://github.com/SunnatilloShavkatov/chuck_interceptor

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ">=0.13.0-0 <1.0.0"
  dio: ">=4.0.0-0 <5.0.0"
  flutter_local_notifications: ">=9.5.0-0 <10.0.0"
  rxdart: ">=0.27.0-0 <1.0.0"
  path_provider: ">=2.0.0-0 <3.0.0"
  permission_handler: ">=10.0.0-0 <12.0.0"
  package_info_plus: ">=1.0.0-0 <2.0.0"
  open_file: ">=3.0.0-0 <4.0.0"
  sensors: ">=2.0.0-0 <3.0.0"
  share_plus: ">=4.0.0-0 <5.0.0"
  chopper: ">=4.0.0-0 <5.0.0"
  collection: ">=1.0.0-0 <2.0.0"

dev_dependencies:
  flutter_lints: ^2.0.1
