name: chuck_interceptor
description: Chuck Intercepter is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 0.0.7
homepage: https://github.com/SunnatilloShavkatov/chuck_interceptor

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  dio: ^4.0.3
  flutter_local_notifications: ^9.1.3
  rxdart: ^0.27.2
  path_provider: ^2.0.7
  permission_handler: ^8.2.6
  package_info_plus: ^1.3.0
  open_file: ^3.2.1
  sensors: ^2.0.3
  share: ^2.0.4
  chopper: ^4.0.3
  collection: ^1.15.0

dev_dependencies:
  flutter_lints: ^1.0.4
