name: chuck_interceptor
description: Chuck is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 1.0.1
homepage: https://github.com/SunnatilloShavkatov/chuck_interceptor

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  dio: ^4.0.6
  flutter_local_notifications: ^9.6.1
  rxdart: ^0.27.4
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  package_info_plus: ^1.4.2
  open_file: ^3.2.1
  sensors: ^2.0.3
  share_plus: ^4.0.10
  chopper: ^4.0.6
  collection: ^1.16.0

dev_dependencies:
  flutter_lints: ^2.0.1
