name: chuck_interceptor
description: Chuck is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 2.1.6
homepage: https://github.com/SunnatilloShavkatov/chuck_interceptor

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ">=5.4.3 <6.0.0"
  http: ">=0.13.5-0 <2.0.0"
  rxdart: ^0.27.7
  share_plus: ^9.0.0
  path_provider: ^2.1.3
  package_info_plus: ^8.0.0
  permission_handler: ">=11.3.1-0 <14.0.0"
  flutter_local_notifications: ^17.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
  flutter_lints: ^3.0.1